apiVersion: kind.x-k8s.io/v1alpha4
kind: Pod
featureGates:
  MatchLabelKeysInPodTopologySpread: true
metadata: 
  name: my-pod1
spec:
  containers:
    - image: nginx:1.12
      name: nginx
      ports:
        -containerPort: 80